### ISSUE TITLE
Fix uncaught  exception on running help

### ISSUE THREAD

**Issue by jappeace** [jappeace/cut-the-crap#19]

**Comment by Ariakenom** [comment]
Hey. I had a look at this and it appears optparse throws an `ExitFailure` when it parsing the options fails. 

Is there a reason why all exceptions are caught in main? Otherwise I am just going to remove that catch. The programs exits correctly without it.

**Comment by jappeace** [comment]
Hi @Ariakenom if that fixes it, that's a good idea, have you tried seeing what blame says on that commit? It is maybe just some debugging line.

**Comment by Ariakenom** [comment]
That commit didn't say anything related to this line so that seems likely.

**Comment by jappeace** [comment]
Looking forward to your PR then 😉

**Comment by jappeace** [comment]
Solved by @Ariakenom
